### ISSUE TITLE
骗人，明明没有支持浮点型。

### ISSUE THREAD

**Issue by jingquanxie** [hedge-hog/RatingBar#10]
RT

**Comment by hedge-hog** [comment]
新的代码已经上传了，可以支持半颗星，但因为这个控件继承的Imageview，所以对半颗星的支持的不是很好，不是很建议采用，你可以看看源码，如果有什么更好的解决方法，可以告诉我。哦，对了，网络问题，一直上传不上Jcenter

**Comment by hedge-hog** [comment]
已经成功上传Jcenter了，你可以看看！
