### ISSUE TITLE
No love_half in mipmap

### ISSUE THREAD

**Issue by hwding** [hedge-hog/RatingBar#11]
asset 'love_half' is missing, please fix this issue!

**Comment by hedge-hog** [comment]
love那个icon是我最早版本的，那时候没有设置半颗星，你可以去mipmap-xhdpi里看看，有star-half，我代码上传github了，但是因为网络的原因（你懂得）暂时不能上传到Jcenter。

**Comment by hwding** [comment]
@hedge-hog
OK，项目需要个人认为心型也许是个好选择，所以现在委屈一下吧浮点转换成了整型。
还是希望JCenter能更新出love-half，要是有不同颜色的选择也许会更好，支持中 :)

**Comment by hwding** [comment]
@hedge-hog 
还有，不同dpi里的有些是star_fill有些是star_full，这个貌似有点...

**Comment by hedge-hog** [comment]
因为有一部分代码是另外一个人提交的，刚刚借用别人的网络已经上传到Jcenter了，马上修改Readme，你可以看看。

**Comment by hwding** [comment]
@hedge-hog 
感谢。

**Comment by hedge-hog** [comment]
已经修改好了，代码写的很烂，仅供参考。

**Comment by hwding** [comment]
@hedge-hog 
作为展示蛮好用的，有机会咱给改改 :)
