### ISSUE TITLE
app:clickable="false" 无效

### ISSUE THREAD

**Issue by howtoplay** [hedge-hog/RatingBar#12]
我只想在界面展示，不想用户通过点击改变星星的数目，可是我设置了app:clickable="false"，却没有效果，还是可以点击改变星星数目。

看了你的代码，我觉得你在判断里写错了，

`if (mClickable && halfstart) {`

改成

```
if (mClickable) {
	if (halfstart) {
```

就可以了

**Comment by hedge-hog** [comment]
哎呀！大意了！（小岳岳脸）
已经修改上传了....
多谢！
