### ISSUE TITLE
HalfStart is not work

### ISSUE THREAD

**Issue by lingguohui** [hedge-hog/RatingBar#4]
The RatingBar constructor should be add below:
starHalfDrawable = mTypedArray.getDrawable(R.styleable.RatingBar_starHalf);

**Comment by LondonX** [comment]
Override the constructor like this is working for me
`public class MyRatingBar extends RatingBar {
    public MyRatingBar(Context context, AttributeSet attrs) {
        super(context, attrs);
        TypedArray mTypedArray = context.obtainStyledAttributes(attrs,
                com.hedgehog.ratingbar.R.styleable.RatingBar);
        Drawable halfDrawable = mTypedArray.getDrawable(
                com.hedgehog.ratingbar.R.styleable.RatingBar_starHalf);
        mTypedArray.recycle();
        setStarHalfDrawable(halfDrawable);
    }
}`

**Comment by hedge-hog** [comment]
halfstar is ok！
