### ISSUE TITLE
On a second start I get NullPointerException

### ISSUE THREAD

**Issue by Seishin** [hedge-hog/RatingBar#5]
When I try to start the app for second time, I receive a NullPointerException in the MainActivity of the RatingBar library... It's because it couldn't set a listener on the rating bar.

**Comment by hedge-hog** [comment]
sorry I did not run into this error， check your code again

       RatingBar mRatingBar = (RatingBar) findViewById(R.id.ratingbar);
        mRatingBar.setOnRatingChangeListener(
                new RatingBar.OnRatingChangeListener() {
                    @Override
                    public void onRatingChange(int RatingCount) {
                            Toast.makeText(MainActivity.this,"the fill star is"+RatingCount,Toast.LENGTH_LONG).show();
                    }
                }
        );
