### ISSUE TITLE
Remove Intent filter from Manifest in library

### ISSUE THREAD

**Issue by Pareshoct7** [hedge-hog/RatingBar#6]
it generates two launchers one for app and other one for library so please remove intent filter from Manifest of library .

it will solve the two launcher issue..

sorry for bad English.

**Comment by bluemix** [comment]
yes, the same for me, having two icons of my app.

**Comment by lywhlao** [comment]
yes,the same. I copy the source code,then remove the "Intent filter" in AndroidManifest.xml .then ok

**Comment by hedge-hog** [comment]
Thanks you guys

I almost think I solved the problem

sorry for bad English.

**Comment by Pareshoct7** [comment]
@hedge-hog 
Yes you did nice job thaks
