### ISSUE TITLE
padding的值都没有调用啊。。。。。。。

### ISSUE THREAD

**Issue by andansky** [hedge-hog/RatingBar#9]
/**
     * @param context
     * @param attrs
     * @return
     */
    private ImageView getStarImageView(Context context, AttributeSet attrs) {
        ImageView imageView = new ImageView(context);
        ViewGroup.LayoutParams para = new ViewGroup.LayoutParams(
                Math.round(starImageSize),
                Math.round(starImageSize)
        );
        imageView.setLayoutParams(para);
        imageView.setPadding(0, 0, 5, 0);
        imageView.setImageDrawable(starEmptyDrawable);
        imageView.setMaxWidth(10);
        imageView.setMaxHeight(10);
        return imageView;

    }
padding的值只有默认的5呢。为什么不把参数带上呢？

**Comment by hedge-hog** [comment]
参数带上了，代码更新了，你可以看看
